name: 'MergeBot'
description: 'MergeBot merges open PRs in a safe manner'
author: 'Sketch'
inputs:
  github-token:
    required: true
    description: 'Github token used to apply changes to the Pull Request'
  base-branch:
    required: false
    default: main
    description: 'Name of the default branch where the bot should merge Pull Requests'
  merge-method:
    required: false
    default: squash
    description: 'Method used to merge a Pull Request, possible values are: merge, rebase or squash'
  grace-time:
    required: false
    default: 0
    description: 'Time (in ms) this script waits before even start. This gives some time for contributors to remove a wrong label'
  merge-label:
    required: false
    default: ready-to-merge
    description: 'Name of the label used to tag PRs as ready-to-merge'
  block-label:
    required: false
    default: do-not-merge
    description: 'Name of the label used to block merges. If this option is present, MergeQueue will never merge this Pull Request'
  error-label:
    required: false
    default: unable-to-merge
    description: "Name of the label used to notify that MergeBot can't merge a Pull Request"
runs:
  using: 'node12'
  main: 'dist/index.js'
