name: 'Main branch CI'
on:
  push:
    branches:
      - main

jobs:
  merge-queue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MergeQueue
        uses: ./
        with:
          github-token: ${{ secrets.MERGE_QUEUE_GH_TOKEN }}
