name: 'Pull Request CI'
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
  merge-queue:
    runs-on: ubuntu-latest
    needs: [sleep]
    steps:
      - uses: actions/checkout@v2
      - name: MergeQueue
        uses: ./
        with:
          github-token: ${{ secrets.MERGE_QUEUE_GH_TOKEN }}
